//
// File generated by HDevelop for HALCON/.NET (C#) Version 18.11.0.1
// Non-ASCII strings in this file are encoded in UTF-8.
// 
// Please note that non-ASCII characters in string constants are exported
// as octal codes in order to guarantee that the strings are correctly
// created on all systems, independent on any compiler settings.
// 
// Source files with different encoding should not be mixed in one project.
//
//  This file is intended to be used with the HDevelopTemplate or
//  HDevelopTemplateWPF projects located under %HALCONEXAMPLES%\c#

using System;
//using HalconDotNet;
using CommonLibrary;

namespace ImageIdentityLibrary
{
    public partial class ImageIdentityClass
    {
        // 定义一个显示事件
        public event smEventHandler showMessageEvent;
        //public HTuple hv_ExpDefaultWinHandle;
        /*public void InitHalcon()
        {
          // Default settings used in HDevelop
          HOperatorSet.SetSystem("width", 512);
          HOperatorSet.SetSystem("height", 512);
        }*/
        // Main procedure 
        /// <summary>
        /// 该函数为工业相机图像识别函数，
        /// </summary>
        /// <param name="hv_ExpDefaultWinHandle">显示控件</param>
        /// <param name="Image">相机图像</param>
        /// <param name="Result">图像处理结果 0、完好 -1、XX损坏 -2、异常</param>
        //public int identifyAction(HTuple hv_ExpDefaultWinHandle, HObject Image, out HObject ResultImage)// 1:增加两个参数
        //{
        //    // Local iconic variables 

        //    HObject ho_Image, ho_GrayImage;

        //    // Local control variables 

        //    HTuple hv_Width = new HTuple(), hv_Height = new HTuple();
        //    // Initialize local and output iconic variables 
        //    HOperatorSet.GenEmptyObj(out ho_Image);
        //    HOperatorSet.GenEmptyObj(out ho_GrayImage);
        //    //dev_close_window(...);
        //    ho_Image.Dispose();
        //    //HOperatorSet.ReadImage(out ho_Image, "1.jpg");
        //    ho_Image = Image;// 2:图像传入
        //    ho_GrayImage.Dispose();
        //    HOperatorSet.Rgb1ToGray(ho_Image, out ho_GrayImage);
        //    hv_Width.Dispose(); hv_Height.Dispose();
        //    HOperatorSet.GetImageSize(ho_Image, out hv_Width, out hv_Height);
        //    //dev_open_window(...);
        //    HOperatorSet.DispObj(ho_GrayImage, hv_ExpDefaultWinHandle);
        //    ho_Image.Dispose();
        //    ho_GrayImage.Dispose();

        //    hv_Width.Dispose();
        //    hv_Height.Dispose();
        //    hv_ExpDefaultWinHandle.Dispose();

        //    ResultImage = ho_GrayImage;  // 3:处理后图像传出          

        //    showMessageEvent("提示信息。");
        //    showMessageEvent("警告信息！", InfoType.Warn);
        //    showMessageEvent("错误信息！", InfoType.Error);
        //    showMessageEvent("调试信息。", InfoType.Debug);
        //    return 0;
        //}       
    }
}
